name: Build APK (sans EAS)

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 36
          build-tools: 36.0.0
          cmake: 3.22.1

      - name: Accept Android licences
        run: yes | sdkmanager --licenses || true

      - name: Expo prebuild
        run: npx expo prebuild --platform android --no-install

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build APK
        working-directory: android
        run: ./gradlew assembleRelease --no-daemon --max-workers=2

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release.apk
